version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      time: "04:35"
    open-pull-requests-limit: 10
    target-branch: dev/main
    labels:
      - dependencies
