name: Publish To Nuget

on:
#  pull_request:
#  push:
#  release:
#    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build:
    name: Build
    runs-on: windows-latest
    environment: Default
    env:
      NUPKG_MAJOR: 1.0.0
#      CODESIGN_PFX: ${{ secrets.CODESIGN_PFX }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: latest
      - name: Install MAUI workload
        run: dotnet workload install maui
      - name: Build
        run: dotnet build -c Release
      - name: Package NuGets
        shell: pwsh
        run: |
          $VERSION="$env:NUPKG_MAJOR-ci$env:GITHUB_RUN_ID"
          if ($env:GITHUB_EVENT_NAME -eq "release") {
            $VERSION = $env:GITHUB_REF.Substring($env:GITHUB_REF.LastIndexOf('/') + 1)
          }
          echo "::set-output name=pkgverci::$VERSION"
          echo "PACKAGE VERSION: $VERSION"
          
          New-Item -ItemType Directory -Force -Path .\artifacts
          dotnet pack --output ./artifacts -c Release -p:PackageVersion=$VERSION
#$pfxPath = Join-Path -Path $pwd -ChildPath "codesigncert.pfx"
#[IO.File]::WriteAllBytes("$pfxPath", [System.Convert]::FromBase64String($env:CODESIGN_PFX))
#nuget sign .\artifacts\*.nupkg -CertificatePath $pfxPath -Timestamper http://timestamp.entrust.net/TSS/RFC3161sha2TS

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nupkg
          path: ./artifacts

  publish:
    name: Publish
    needs: build
    runs-on: windows-latest
    environment: Default
#    if: github.event_name == 'release'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: nupkg
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Push to nuget
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NuGetAPIKey }}
